### ISSUE TITLE
zip & zipWith

### ISSUE THREAD

**Issue by turanct** [mathiasverraes/lambdalicious#13]
wouldn't these be handy list functions?

# zip
takes two lists `a` and `b` as arguments, and returns a list of tuples `(x, y)` where `x` and `y` are corresponding list elements from `a` and `b`

# zipWith
takes a function `f` and two lists `a` and `b`, and returns a list of return values of `f(x, y)` where `x` and `y` are corresponding list elements from `a` and `b`

**idea stolen from Haskell standard library (Prelude)**

**Comment by mathiasverraes** [comment]
If we rename zipwith to map2, we can also have map3, map4 
(at least I think that zipwith === map2)
Of course we could leave zipwith as an alias to map2

**Comment by turanct** [comment]
Yes. I think you're right that `zipWith` equals `map2`.
The thing is, you could then also have `zip3`, `zip4` etc... how far do you want to go with this? :trollface: 

I'll make another pull request for the rename

**Comment by mathiasverraes** [comment]
>> how far do you want to go with this?

until Lambdalicious becomes sentient.




[image: photo]
*Mathias Verraes*
Software Consultant, Value Object Comm.V
mathias@verraes.net | http://value-object.com/
<http://www.linkedin.com/in/mathiasverraes>
<http://twitter.com/mathiasverraes>

**Comment by turanct** [comment]
i hoped so

![whoa](http://replygif.net/i/321.gif)
